name: isar_performance_degration_reproduction_example
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  isar: ^4.0.0-dev.14
  isar_flutter_libs: ^4.0.0-dev.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  isar:
    version: 4.0.3
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs:
    version: 4.0.3
    hosted: https://pub.isar-community.dev/

flutter:
  uses-material-design: true
